---
- name: install httpd
  hosts: nfs
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: enable
      systemd:
        name: httpd
        state: started
        enabled: true

    - name: permit traffic in default zone for https service
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
