---
- nmae: install httpd
  hosts: nfs
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: enable
      systemd:
        name: httpd
        state: started
        enabled: true
