---
- name: install httpd
  hosts: nfs
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: enable
      systemd:
        name: httpd
        state: started
        enabled: true

    - name: Enable firewalld services for http and https
      firewalld:
        service: 
          - http
          - https
        permanent: true
        state: enabled

    - name: Reload firewalld
      firewalld:
        state: reloaded
